---
title: "Aging hallmarks with PAM50 intrinsic subtype analysis"
author: "Jiang Li"
output: html_document
date: "2025-04-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Radar plot of aging hallmark vs PAM50 subtypes
```{r}
aging.corr.analysis<-lapply(aging.gene, function(geneset){
  df<-data.frame(
    'PAM50'=metabric.pheno$PAM50_SUBTYPE,
    'TNBC'=metabric.pheno$TNBC_SUBTYPE,
    'Age_group'=metabric.pheno$age.40.65,
    'Age'=metabric.pheno$AGE_AT_DIAGNOSIS,
    'Gene'=apply(metabric.expr[geneset,],2,mean,na.rm=T)
  )
  pam50.p<-df %>% dplyr::group_by(PAM50) %>% summarise(p.value=cor.test(Age, Gene)$p.value) %>% 
    magrittr::set_colnames(c('subtype','p.value'))
  tnbc.p<-df %>% dplyr::group_by(TNBC) %>% summarise(p.value=cor.test(Age, Gene)$p.value) %>% 
    magrittr::set_colnames(c('subtype','p.value'))
  age.p <-df %>% dplyr::group_by(Age_group) %>% summarise(p.value=cor.test(Age, Gene)$p.value) %>% 
    magrittr::set_colnames(c('subtype','p.value'))
  return(rbind(pam50.p, tnbc.p, age.p) %>% spread(key = subtype, value=p.value))
}) %>% Reduce(rbind,.) %>% as.data.frame() %>% magrittr::set_rownames(names(aging.gene))
aging.corr.analysis<-aging.corr.analysis[,c('Basal','Her2','Normal','LumA','LumB','TNBC','non-TNBC','40-','41-55','56-65','66+')] %>% 
  t() %>% as.data.frame()
aging.corr.analysis<- -log10(aging.corr.analysis)
range(aging.corr.analysis)
min.max<-matrix(c(20,0), byrow = F, nrow = 2, ncol = ncol(aging.corr.analysis),
                dimnames = list(rownames=c('Max','Min'), colnames=colnames(aging.corr.analysis))) %>% 
  as.data.frame()
aging.corr.analysis<-rbind(min.max, aging.corr.analysis)
rm(min.max)
aging.corr.analysis.tnbc <- aging.corr.analysis[c("Max", "Min", "non-TNBC","TNBC"), ]

aging.corr.analysis['Max',] <- 10
fmsb::radarchart(
  aging.corr.analysis[c("Max", "Min",'Basal','Her2','LumA','LumB','Normal'), ], axistype = 1,
  # Customize the polygon
  pcol = c('#462255','#AA4465','#FFA69E','#93E1D8','#004CAA'), 
  pfcol = scales::alpha(c('#462255','#AA4465','#FFA69E','#93E1D8','#004CAA'), 0), plwd = 2, plty = 1,
  # Customize the grid
  cglcol = "grey", cglty = 'dashed', cglwd = 0.8,
  # Customize the axis
  axislabcol = "black", 
  # Variable labels
  vlcex = 1.3, vlabels = colnames(aging.corr.analysis),
  caxislabels = c(0, 2,5,8,10), title = ''
)

fmsb::radarchart(
  aging.corr.analysis.tnbc, axistype = 1,
  # Customize the polygon
  pcol = c('#5E98D3', '#D86364'), pfcol = scales::alpha(c('#5E98D3', '#D86364'), 0), 
  plwd = 2, plty = 1,
  # Customize the grid
  cglcol = "grey", cglty = 'dashed', cglwd = 0.8,
  # Customize the axis
  axislabcol = "black", 
  # Variable labels
  vlcex = 1.3, vlabels = colnames(aging.corr.analysis.tnbc),
  caxislabels = c(0, 5, 10, 15, 20), title = ''
)

aging.corr.analysis.age <- aging.corr.analysis[c("Max", "Min", '40-','41-55','56-65','66+'), ]
aging.corr.analysis.age['Max',] <- 3
fmsb::radarchart(
  aging.corr.analysis.age, axistype = 1,
  # Customize the polygon
  pcol = c('#DE7A64','#3F405A','#F1C986','#83B29E'), 
  pfcol = scales::alpha(c('#DE7A64','#3F405A','#F1C986','#83B29E'), 0), 
  plwd = 2, plty = 1,
  # Customize the grid
  cglcol = "grey", cglty = 'dashed', cglwd = 0.8,
  # Customize the axis
  axislabcol = "black", 
  # Variable labels
  vlcex = 1.3, vlabels = colnames(aging.corr.analysis.age),
  caxislabels = c(0, 1, 1.5, 2, 3), title = ''
)
```

